/*

HTML-WRITTEN FILE || Script sequence: [1]

*/

var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(a==Array.prototype||a==Object.prototype)return a;a[c]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var d=a[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";$jscomp.polyfill=function(a,c,d,e){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,d,e):$jscomp.polyfillUnisolated(a,c,d,e))};
$jscomp.polyfillUnisolated=function(a,c){var d=$jscomp.global;a=a.split(".");for(var e=0;e<a.length-1;e++){var b=a[e];if(!(b in d))return;d=d[b]}a=a[a.length-1];e=d[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,d){var e=a.split(".");a=1===e.length;var b=e[0];b=!a&&b in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in b))return;b=b[g]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?b[e]:null;c=c(d);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==d&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,
e=$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(b,e,{configurable:!0,writable:!0,value:c})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var c=function(b,f){this.$jscomp$symbol$id_=b;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};c.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,e=function(b){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(b||"")+"_"+d++,b)};return e},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var c="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<c.length;d++){var e=$jscomp.global[c[d]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&$jscomp.defineProperty(e.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,c){a instanceof String&&(a+="");var d=0,e=!1,b={next:function(){if(!e&&d<a.length){var f=d++;return{value:c(f,a[f]),done:!1}}e=!0;return{done:!0,value:void 0}}};b[Symbol.iterator]=function(){return b};return b};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:a=function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");window.yterr=window.yterr||!0;window.unhandledErrorMessages={};window.unhandledErrorCount=0;
window.onerror=function(a,c,d,e,b){b||(b=Error(),b.stack="",b.message=a,b.fileName=c,b.lineNumber=d,isNaN(e)||(b.columnNumber=e));d=String(b.message);if(!(!b.message||d in window.unhandledErrorMessages||5<=window.unhandledErrorCount)){window.unhandledErrorCount+=1;window.unhandledErrorMessages[d]=!0;a=new Image;window.emergencyTimeoutImg=a;a.onload=a.onerror=function(){delete window.emergencyTimeoutImg};e=b.lineNumber;isNaN(b.columnNumber)||(e+=":"+b.columnNumber);c=b.stack||"";b={msg:d,type:b.name,
"client.params":"unhandled window error",file:b.fileName,line:e,stack:c.substr(0,500)};try{var f=c.replace(/https:\/\/www.youtube.com\//g,"");f.match(/https?:\/\/[^/]+\//)&&(b.level="WARNING")}catch(k){b["client.params.monitor_error"]=String(k)}f=[window.ytcfg.get("EMERGENCY_BASE_URL","https://www.youtube.com/error_204?t=jserror&level=ERROR")];for(var g in b)(c=b[g])&&f.push(g+"="+encodeURIComponent(c));a.src=f.join("&")}};
(function(){function a(f){var g=this._nativePrototypes[f];if(!g){g=Object.create(this.getNativePrototype(f));for(var k=Object.getOwnPropertyNames(window.Polymer.Base),l=0,h;l<k.length&&(h=k[l]);l++)if(!window.Polymer.BaseDescriptors[h])try{g[h]=window.Polymer.Base[h]}catch(m){throw Error("Error while copying property: "+h+". Tag is "+f);}try{Object.defineProperties(g,window.Polymer.BaseDescriptors)}catch(m){throw Error("Polymer define property failed for "+Object.keys(g));}this._nativePrototypes[f]=
g}return g}function c(f){window.onerror(f,window.location.href,0,0,Error(Array.prototype.join.call(arguments,",")))}var d=window.Polymer,e=function(f){!d._ytIntercepted&&window.Polymer.Base&&(d._ytIntercepted=!0,window.Polymer.Base._getExtendedNativePrototype=a,window.Polymer.Base._error=c,window.Polymer.Base._warn=c);return d.apply(this,arguments)},b=Object.getOwnPropertyDescriptor(window,"Polymer");Object.defineProperty(window,"Polymer",{set:function(f){b&&b.set&&b.get?(b.set(f),d=b.get()):d=f;
"function"==typeof d&&Object.defineProperty(window,"Polymer",{value:d,configurable:!0,enumerable:!0,writable:!0})},get:function(){return"function"==typeof d?e:d},configurable:!0,enumerable:!0})})();
