/*

Base URL: /dext5/js/dext5editor.js || Script sequence: [0]

*//*
 Copyright (c) 2013, Raonwiz Technology Inc. All rights reserved.
*/
window.DEXT5||(window.DEXT5=function(){var a=window.DEXT5_ROOTPATH||"";if(!a)for(var c=document.getElementsByTagName("script"),b=c.length,e=null,h=0;h<b;h++){var e=c[h],g=e.src.match(/(^|.*[\\\/])dext5editor.js(?:\?.*)?$/i);"samsung.net"==document.domain&&(g=e.src.match(/(^|.*[\\\/])helloeditor.js(?:\?.*)?$/i));if(g){a=g[1];break}}-1==a.indexOf(":/")&&(a=0===a.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+a:location.href.match(/^[^\?]*\/(?:)/)[0]+a);a=a.split("/js")[0]+"/";if(!a)throw"DEXT5 installation path could not be automatically detected.";
return{isRelease:!0,cabVersion:"1,0,0,119",version:"DEXT5 Editor",ReleaseVer:"987889.1642.01",rootPath:a,DEXTMULTIPLE:{}}}(),DEXT5.brower||(DEXT5.browser=function(){var a=navigator.userAgent.toLowerCase(),c=window.opera,c={ie:-1<a.search("trident")||-1<a.search("msie")?!0:!1,opera:!!c&&c.version,webkit:-1<a.indexOf(" applewebkit/"),mac:-1<a.indexOf("macintosh"),quirks:"BackCompat"==document.compatMode,mobile:-1<a.indexOf("mobile"),iOS:/(ipad|iphone|ipod)/.test(a),isCustomDomain:function(){if(!this.ie)return!1;
var a=document.domain,b=window.location.hostname;return a!=b&&a!="["+b+"]"},isHttps:"https:"==location.protocol};c.gecko="Gecko"==navigator.product&&!c.webkit&&!c.opera;c.ie&&(c.gecko=!1);c.webkit&&(-1<a.indexOf("chrome")?(c.chrome=!0,-1<a.indexOf("opr")&&(c.opera=!0,c.chrome=!1)):c.safari=!0);var b;c.ieVersion=0;c.ie&&(b=c.quirks||!document.documentMode?-1<a.indexOf("msie")?parseFloat(a.match(/msie (\d+)/)[1]):-1<a.indexOf("trident")?parseFloat(a.match(/rv:([\d\.]+)/)[1]):7:document.documentMode,
c.ieVersion=b,c.ie11=11==b,c.ie10=10==b,c.ie9=9==b,c.ie8=8==b,c.ie7=7==b,c.ie6=7>b||c.quirks);c.gecko&&(b=a.match(/rv:([\d\.]+)/))&&(b=b[1].split("."),b=1E4*b[0]+100*(b[1]||0)+1*(b[2]||0));c.webkit&&(b=parseFloat(a.match(/ applewebkit\/(\d+)/)[1]));return c}()));
DEXT5.config={Width:"",Height:"",SkinName:"",InitXml:"",ToSavePathURL:"",ToSaveFilePathURL:"",ServerDomain:"",HandlerUrl:"",InitVisible:!0,DefaultMessage:"",FirstLoadType:"",FirstLoadMessage:"",FileFieldID:"",EditorHolder:"",zTopMenu:"",zToolBar:"",zTopStatusBar:"",zStatusBar:"",zXssUse:"",zXssRemoveTags:"",zXssRemoveEvents:"",Mode:"",zIndex:"",NextTabElementId:"",IgnoreSameEditorName:"0",ChangeMultiValueMode:"",EditorBorder:"",InitLang:"",IconName:"icon",CustomCode:"",EnterTag:"",userFontFamily:"",
userFontSize:"",UserFieldID:"",UserFieldValue:"",LicenseKey:"",mimeCharset:"",mimeConentEncodingType:"",mimeFileTypeFilter:"",mimeLocalOnly:"",mimeRemoveHeader:"",userOpenDlgTitle:"",userOpenDlgType:"",userOpenDlgInitDir:"",userImageDlgStyle:"",mimeBaseURL:"",focusInitObjId:"",pluginUse:"",mimeUse:"",officeLineFix:"",useLog:"0",RootPath:"",EditorTabDisable:""};
DEXT5.ajax=function(){var a=function(){if(!DEXT5.browser.ie||"file:"!=location.protocol){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XHLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}return null},c=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)},b=function(a){return c(a)?a.responseText:null},e=function(a){if(c(a)){var b=a.responseXML;return b?b:a.responseText}return null},
h=function(b,c,d){var f=!!c,e=a();if(!e)return null;e.open("GET",b,f);f&&(e.onreadystatechange=function(){4==e.readyState&&(c(d(e)),e=null)});try{e.send(null)}catch(h){return null}setTimeout(function(){e.abort()},5E3);return f?"":d(e)};return{load:function(a,c){return h(a,c,b)},loadXml:function(a,b){return h(a,b,e)},postData:function(b,c){var d;a:if(d=a()){try{d.open("POST",b,!1),d.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8"),d.send(c)}catch(f){d=null;break a}d=
d.responseText}else d=null;return d},postFileData:function(b,c){var d;a:if(d=a()){try{d.open("POST",b,!1);var f="--------------------"+(new Date).getTime();d.setRequestHeader("Content-Type","multipart/form-data; boundary="+f);for(var f="--"+f,e="",h=c.split("&"),m=h.length,l=null,v="",y="",u=0;u<m;u++)l=h[u].split("="),"imagedata"==l[0]?v=l[1]:(e+=f+"\r\n",e+='Content-Disposition: form-data; name="'+l[0]+'"\r\n\r\n',e+=l[1]+"\r\n");for(var h=null,m="",w=window.atob(v),F=w.length,h=new Uint8Array(new ArrayBuffer(F)),
u=0;u<F;u++)h[u]=w.charCodeAt(u),m+=String.fromCharCode(h[u]);String.fromCharCode.apply([],new Uint8Array(h));new Uint8Array(h);y=m;e+=f+"\r\n";e+='Content-Disposition: form-data; name="Filedata"; filename="'+(new Date).getTime()+'"\r\n';e+="Content-Type: image/png\r\n";e+="\r\n";e+=y+"\r\n";d.send(e+(f+"--\r\n"))}catch(G){d=null;break a}d=d.responseText}else d=null;return d}}}();
DEXT5.util={G_IMG_LIST:{},trim:function(a){return a.trim?a.trim():a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},setClass:function(a,c){a.className=c},getClass:function(a){return a.className},checkUrl:function(a){var c=!1;return c=RegExp(/(http|ftp|https|news):\/\/[\w-]+(\.[\w-]+)+([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/).test(a)},makeIframe:function(){var a;try{a=document.createElement('<iframe frameborder="0" >')}catch(c){a=document.createElement("iframe")}a.style.margin="0px";a.style.padding=
"0px";a.frameBorder=0;a.style.overflow="auto";a.style.overflowX="hidden";a.style.backgroundColor="#ffffff";return a},addEvent:function(a,c,b,e){a.addEventListener?a.addEventListener(c,b,e):a.attachEvent&&a.attachEvent("on"+c,b)},removeEvent:function(a,c,b,e){a.removeEventListener?a.removeEventListener(c,b,e):a.detachEvent&&a.detachEvent("on"+c,b)},stopEvent:function(a){"bubbles"in a?a.bubbles&&a.stopPropagation():a.cancelBubble=!0},cancelEvent:function(a){a.preventDefault?a.preventDefault():a.returnValue=
!1},ajax:{xml_http_request:function(){var a;window.XMLHttpRequest?a=new XMLHttpRequest:window.ActiveXObject&&(a=new ActiveXObject("Microsoft.XMLHTTP"));return a}},url:{full_url:function(a){var c="";if(0==a.indexOf("http://")||0==a.indexOf("https://"))c=a;else if(0==a.indexOf("/"))c=location.protocol+"//"+location.host+a;else var c=location.href,b=c.lastIndexOf("/"),c=c.substring(0,b+1),c=c+a;return c}},xml:{count:function(a,c){return a?a.getElementsByTagName(c).length:0},getNode:function(a,c){return null==
a||void 0==a?null:this.getNodeIdx(a,c,0)},getNodeIdx:function(a,c,b){return a.getElementsByTagName(c)[b]},getNodeValue:function(a,c){return null==a||void 0==a?"":this.getNodeValueIdx(a,c,0)},getNodeValueIdx:function(a,c,b){a=this.getNodeIdx(a,c,b);return this.getValue(a)},getValue:function(a){var c="",b="";if(void 0!=a)try{0<a.childNodes.length&&(b=c=a.firstChild.nodeValue);try{("product_key"==a.nodeName||"font"==a.nodeName||"encoding"==a.nodeName||"doctype"==a.nodeName)&&2<=a.childNodes.length&&
(c=a.textContent?a.textContent:b)}catch(e){c=b}}catch(h){c="parsing error"}return c}},htmlToLowerCase:function(a){if(8<DEXTTOP.DEXT5.browser.ieVersion&&!1==DEXTTOP.DEXT5.browser.quirks)return a;var c=RegExp("<[^>]+>","g");results=a.match(c);if(null==results)return a;var b=c=-1,e=0,h=results.length;for(i=0;i<h;i++){original=results[i];c=original.indexOf("'");b=original.indexOf('"');e=2;1<c*b&&(-1<original.indexOf('="')?(results[i]=results[i].replace(/\'/g,"dext5_1q"),e=2):-1<original.indexOf("='")&&
(results[i]=results[i].replace(/\"/g,"dext5_2q"),e=1));stripquoted=1==e?results[i].replace(/ [^=]+= *\'[^\']*\'/g,""):results[i].replace(/ [^=]+= *"[^"]*"/g,"");c=RegExp(" [^=]+=[^ >]+","g");if(unquoted=stripquoted.match(c))for(c=unquoted.length,j=0;j<c;j++)addquotes=1==e?unquoted[j].replace(/( [^=]+=)([^ >]+)/g,"$1'$2'"):unquoted[j].replace(/( [^=]+=)([^ >]+)/g,'$1"$2"'),results[i]=results[i].replace(unquoted[j],addquotes);results[i]=results[i].replace(/<\/?[^>|^ ]+/,function(a){return a.toLowerCase()});
results[i]=1==e?results[i].replace(/ [^=|^ ]+=\'/g,function(a){return a.toLowerCase()}):results[i].replace(/ [^=|^ ]+="/g,function(a){return a.toLowerCase()});results[i]=results[i].replace(/dext5_1q/g,"'");results[i]=results[i].replace(/dext5_2q/g,'"');a=a.replace(original,results[i])}return a},hexDigits:"0123456789abcdef".split(""),hex:function(a){return isNaN(a)?"00":this.hexDigits[(a-a%16)/16]+this.hexDigits[a%16]},rgb2hex:function(a){a=a.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);if(!(null==a||
4>a.length))return"#"+this.hex(a[1])+this.hex(a[2])+this.hex(a[3])},dextSetAttribute:function(a,c,b,e){"string"==typeof b?0<b.length&&(a.style[c]=b+e):"number"==typeof b&&(a.style[c]=b)},getRealBackgoundImagePath:function(a){return a=a.replace(/url\(\s*(["']?)\s*([^\)]*)\s*\1\s*\)/i,function(a,b,e){return e})},replaceForXSS:function(a,c,b,e){var h=!1;try{if(""!=b)for(var g=b.split(","),k=g.length,d=0;d<k;d++){var f=g[d],p=RegExp("<"+f+"[^>]*>[\\s\\S]*?</"+f+">","gim");!0==p.test(a)&&(h=!0,a=a.replace(p,
""));var t=RegExp("<"+f+"[^>]*>","gi");!0==t.test(a)&&(h=!0,a=a.replace(t,""))}if(""!=e)for(var m=e.split(","),l=m.length,d=0;d<l;d++){var v=m[d],y=RegExp("(?:"+v+')\\s*=\\s*"[^"]*"\\s*',"gi"),u=RegExp("(?:"+v+")\\s*=\\s*'[^']*'\\s*","gi");if(y.test(a)||u.test(a))h=!0,a=a.replace(y,""),a=a.replace(u,"")}if(""!=c)for(var w=c.split(","),F=w.length,d=0;d<F;d++){var G=RegExp("<\\/"+w[d]+">","gi"),H=a.match(RegExp("<"+w[d]+"[^>]*>","gi"));if(H){var h=!0,P=H.length;c="";for(b=0;b<P;b++)c=H[b].toLowerCase(),
c=c.replace("<","&lt;"),c=c.replace(">","&gt;"),a=a.replace(H[b],c);a=a.replace(G,"&lt;/"+w[d]+"&gt;")}}}catch(W){}!1==h&&(a="");return a},removeTags:function(a,c){for(var b=c.split(","),e=null,h=b.length,g=0,k=0;k<h;k++)for(e=a.getElementsByTagName(b[k]),g=e.length,g-=1;0<=g;g--){var d=e[g];d.parentNode.removeChild(d)}},removeEvents:function(a,c,b){a=c.split(",");c=b.length;for(var e=0,h=0;h<c;h++)for(var e=a.length,g=0;g<e;g++)b[h].removeAttribute(a[g])},removeElement:function(a){for(;a.firstChild;)a.parentNode.insertBefore(a.firstChild,
a);a.parentNode.removeChild(a)},officeClean:function(a,c){if(""==a||void 0==a)return"";var b=null,e=[],h=!1;/([:| ])([-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)pt/gi.test(a)&&(h=!0);/([:| ])([:| ][-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)cm/gi.test(a)&&(h=!0);if(!0==h){h=document.createElement("div");h.innerHTML=a;for(var b=h.getElementsByTagName("*"),e=b.length,g=0;g<e;g++){var k=b[g];if(k.style.width){var d=k.style.width.toLowerCase();-1<d.indexOf("pt")?(d=4*parseFloat(d)/3,0<d&&1>d&&(d=1),0>d&&
(d=0),d=Math.round(d)+"px",k.style.width=d):-1<d.indexOf("cm")&&(_cm=37.795275593333*parseFloat(d),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),d=Math.round(_cm)+"px",k.style.width=d)}k.style.height&&(d=k.style.height.toLowerCase(),-1<d.indexOf("pt")?(d=4*parseFloat(d)/3,0<d&&1>d&&(d=1),0>d&&(d=0),d=Math.round(d)+"px",k.style.height=d):-1<d.indexOf("cm")&&(_cm=37.795275593333*parseFloat(d),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),d=Math.round(_cm)+"px",k.style.height=d));""!=k.style.borderTop&&(k.style.borderTop=
replacePtOrCmToPx(k.style.borderTop));""!=k.style.borderRight&&(k.style.borderRight=replacePtOrCmToPx(k.style.borderRight));""!=k.style.borderBottom&&(k.style.borderBottom=replacePtOrCmToPx(k.style.borderBottom));""!=k.style.borderLeft&&(k.style.borderLeft=replacePtOrCmToPx(k.style.borderLeft));""!=k.style.borderWidth&&(k.style.borderWidth=replacePtOrCmToPx(k.style.borderWidth))}a=h.innerHTML}a=a.replace(/\.0px/g,"px");a=a.replace(/\t/g,"");b=RegExp("<o:p></o:p>","gi");a=a.replace(b,"");b=RegExp("<o:p>\\s+</o:p>",
"gi");a=a.replace(b,"");b=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(b,"");b=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");a=a.replace(b,"");a=a.replace(/\slang=[\"]?en-us[\"]?/gi,"");a=a.replace(/\sclass=[\"]?(mso)\w+[\"]?/gi,"");b=RegExp('mso-[^:]+:[^;">]+;',"gi");a=a.replace(b,"");b=RegExp('mso-[^:]+:[^;">]+("|\')',"gi");a=a.replace(b,"$1");a=DEXT5.util.replaceAll(a,"hairline","dotted");for(h=0;5>h;h++){e=["o:p","span","font"];k=e.length;for(g=0;g<k;g++)b=RegExp("<"+e[g]+"[^>]*></"+e[g]+">","gi"),
a=a.replace(b,""),b=RegExp("<"+e[g]+"[^>]*>&nbsp;</"+e[g]+">","gi"),a=a.replace(b,"&nbsp;"),b=RegExp("<"+e[g]+"[^>]*> </"+e[g]+">","gi"),a=a.replace(b,"&nbsp;");e=["o","v","w","m","x"];k=e.length;for(g=0;g<k;g++)0==g&&(a=a.replace(/<o:p/gi,"<dexto:p")),b=RegExp("<"+e[g]+":[^/>]+/>","gi"),a=a.replace(b,""),b=RegExp("<"+e[g]+":[^>]+>[^<]*</"+e[g]+":[^>]+>","gi"),a=a.replace(b,""),g==k-1&&(a=a.replace(/<dexto:p/gi,"<o:p"))}a=a.replace(/style=""/gi,"");a=a.replace(/style=''/gi,"");a=a.replace(/\s>/gi,
">");a=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(a);a=a.replace(/>\s+</g,"><");a=a.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");if(DEXTTOP.DEXT5.browser.ie&&10>DEXTTOP.DEXT5.browser.ieVersion){var b=a.length,g=e=!1,f=d=k="";if(-1==a.indexOf("<")&&-1==a.indexOf(">"))for(h=0;h<b;h++)k=a.charAt(h),d=a.charAt(h+1)," "!=k&&32!=k.charCodeAt(0)||" "!=d&&32!=d.charCodeAt(0)||(k="&nbsp;"),f+=k;else for(h=0;h<b;h++)k=a.charAt(h),d=a.charAt(h+1),"<"==k?(e=!1,g="p"==d.toLowerCase()?!0:!1):">"==k&&!0==g?e=!0:!0!=
e||(" "!=k&&32!=k.charCodeAt(0)||" "!=d&&32!=d.charCodeAt(0))||(k="&nbsp;"),f+=k;a=f}!1==c&&(a=DEXTTOP.DEXT5.util.removeLocalFileImage(a));return a},removeLocalFileImage:function(a){if(""==a||void 0==a)return"";a=a.replace(/file:\/\/\//gi,"dext_local_file_image");reg_exp=RegExp("<img[^>]+dext_local_file_image[^>]+>","gi");return a=a.replace(reg_exp,"")},html2xhtml:function(a){if(""==a||void 0==a)return"";for(var c="area base br col embed frame hr img input link meta param".split(" "),b=c.length,e=
null,h=RegExp(),g=0;g<b;g++)e=c[g],h=RegExp("<"+e+" ([^>]*)>","gi"),a=a.replace(h,"<"+e+" $1 />"),h=RegExp("<"+e+">","gi"),a=a.replace(h,"<"+e+" />");return a},emptyTagRemove:function(a){if(""==a||void 0==a)return"";try{if("1"==DEXTTOP.G_CURREDITOR._config.empty_tag_remove){var c=document.createElement("div");c.innerHTML=a;for(var b=c.getElementsByTagName("p"),e=b.length,h,g,k="",d=[],f=["br","img","a","hr","table"],p=!1,t=0;t<e;t++)if(h=b[t],k="textContent"in h?h.textContent:h.innerText,""==k){g=
h.innerHTML;for(var p=!1,m=f.length,l=0;l<m;l++)if(-1<g.toLowerCase().indexOf("<"+f[l])){p=!0;break}!1==p&&d.push(h)}for(var v=d.length;0<v;)h=d.pop(),h.parentNode.removeChild(h);a=c.innerHTML}}catch(y){}return a},emptyTagRemoveCheckInContentTag:function(a,c){if(""==a||void 0==a)return"";try{if("1"==DEXTTOP.G_CURREDITOR._config.empty_tag_remove){var b=document.createElement("div");b.innerHTML=a;for(var e=b.getElementsByTagName("p"),h=e.length,g,k,d="",f=[],p=!1,t=0;t<h;t++)if(g=e[t],d="textContent"in
g?g.textContent:g.innerText,""==d){k=g.innerHTML;for(var p=!1,m=c.length,l=0;l<m;l++)if(-1<k.toLowerCase().indexOf("<"+c[l])){p=!0;break}!1==p&&f.push(g)}for(var v=f.length;0<v;)g=f.pop(),b.removeChild(g);a=b.innerHTML}}catch(y){}return a},htmlRevision:function(a){if(""==a||void 0==a)return"";var c=null;a=a.replace(/\x3c!--[\w\s\d@{}:.;,'"%!#_=&|?~()[*+\/\-\]]*--\x3e/gi,"");DEXT5.browser.ie&&11>DEXT5.browser.ieVersion?(c=RegExp("><p><br></p></td>","gi"),a=a.replace(c,"><p>&nbsp;</p></td>")):(c=RegExp(">&nbsp;</td>",
"gi"),a=a.replace(c,"><p><br></p></td>"));DEXT5.browser.ie&&11>DEXT5.browser.ieVersion?(c=RegExp("<p><br></p>","gi"),a=a.replace(c,"<p>&nbsp;</p>"),c=RegExp("<p><br/></p>","gi"),a=a.replace(c,"<p>&nbsp;</p>"),c=RegExp("<p><br /></p>","gi"),a=a.replace(c,"<p>&nbsp;</p>"),c=RegExp("<p></p>","gi"),a=a.replace(c,"<p>&nbsp;</p>"),c=RegExp("<p>\\s+</p>","gi"),a=a.replace(c,"<p>&nbsp;</p>"),c=RegExp("<p ([^>]+)></p>","gi"),a=a.replace(c,"<p $1>&nbsp;</p>"),c=RegExp("<p ([^>]+)>\\s+</p>","gi"),a=a.replace(c,
"<p $1>&nbsp;</p>")):(c=RegExp("<p></p>","gi"),a=a.replace(c,"<p><br></p>"),c=RegExp("<p>\\s+</p>","gi"),a=a.replace(c,"<p><br></p>"),c=RegExp("<p ([^>]+)></p>","gi"),a=a.replace(c,"<p $1><br></p>"),c=RegExp("<p ([^>]+)>\\s+</p>","gi"),a=a.replace(c,"<p $1><br></p>"));DEXT5.browser.ie&&11>DEXT5.browser.ieVersion?(c=RegExp("<div><br></div>","gi"),a=a.replace(c,"<div>&nbsp;</div>"),c=RegExp("<div><br/></div>","gi"),a=a.replace(c,"<div>&nbsp;</div>"),c=RegExp("<div><br /></div>","gi"),a=a.replace(c,
"<div>&nbsp;</div>"),c=RegExp("<div></div>","gi"),a=a.replace(c,"<div>&nbsp;</div>"),c=RegExp("<div>\\s+</div>","gi"),a=a.replace(c,"<div>&nbsp;</div>"),c=RegExp("<div ([^>]+)></div>","gi"),a=a.replace(c,"<div $1>&nbsp;</div>"),c=RegExp("<div ([^>]+)>\\s+</div>","gi"),a=a.replace(c,"<div $1>&nbsp;</div>")):(c=RegExp("<div></div>","gi"),a=a.replace(c,"<div><br></div>"),c=RegExp("<div>\\s+</div>","gi"),a=a.replace(c,"<div><br></div>"),c=RegExp("<div ([^>]+)></div>","gi"),a=a.replace(c,"<div $1><br></div>"),
c=RegExp("<div ([^>]+)>\\s+</div>","gi"),a=a.replace(c,"<div $1><br></div>"));return a},nbspRemove:function(a){if(""==a||void 0==a)return"";var c=null,c=RegExp("<p>&nbsp;</p>","gi");a=a.replace(c,"<p></p>");c=RegExp("<p ([^>]+)>&nbsp;</p>","gi");return a=a.replace(c,"<p $1></p>")},ImageSrcConvert:function(a,c,b){var e=document.createElement("div");e.innerHTML=a;a=e.getElementsByTagName("img");var h=a.length,g=null,k="",d="";b+="_dext5_base64_image_";for(var f=0;f<h;f++)g=a[f],d=b+f,k=g.src,!0==c?
-1<k.indexOf("data:image")&&-1<k.indexOf("base64,")&&(this.G_IMG_LIST[d]=k,g.src=d):-1<k.indexOf(b)&&(g.src=this.G_IMG_LIST[d],this.G_IMG_LIST[d]="");return a=e.innerHTML},getUrlString:function(a){a=DEXT5.util.replaceAll(a," ","%20");a=DEXT5.util.replaceAll(a,"&nbsp;","%21");a=DEXT5.util.replaceAll(a,"!","%20");a=DEXT5.util.replaceAll(a,'"',"%22");a=DEXT5.util.replaceAll(a,"#","%23");a=DEXT5.util.replaceAll(a,"$","%24");a=DEXT5.util.replaceAll(a,"%","%25");a=DEXT5.util.replaceAll(a,"&","%26");a=DEXT5.util.replaceAll(a,
"'","%27");a=DEXT5.util.replaceAll(a,"+","%2B");a=DEXT5.util.replaceAll(a,"/","%2F");a=DEXT5.util.replaceAll(a,":","%3A");a=DEXT5.util.replaceAll(a,";","%3B");a=DEXT5.util.replaceAll(a,"<","%3C");a=DEXT5.util.replaceAll(a,"=","%3D");a=DEXT5.util.replaceAll(a,">","%3E");a=DEXT5.util.replaceAll(a,"?","%3F");return a=DEXT5.util.replaceAll(a,"@","%40")},replaceAll:function(a,c,b){for(var e=a.indexOf(c);-1!=e;)a=a.replace(c,b),e=a.indexOf(c);return a},getSkinNames:function(){return"blue brown darkgray gold gray green orange pink purple red silver yellow".split(" ")},
CustomSetting:function(a,c,b){switch(a){case "function":CustomSettingFunction(b);break;case "remove_item":return CustomRemoveItem(c)}},replaceOneSpaceToNbsp:function(a){var c=a,b,e="",h=DEXTTOP.G_CURREDITOR._config.plugInUse;try{var g="span font a b strong i em strike u sup sub".split(" "),k=g.length;if("1"==h)for(var d=0;d<k;d++)for(var f=0;f<k;f++){e=c;b=RegExp("<"+g[d]+" *([^>?+])*>(\\s+)</"+g[f]+">","gi");reg_exp2=RegExp("</"+g[d]+">(\\s+)<"+g[f]+" *([^>?+])*>","gi");try{var p=c.match(b);if(p)for(var t=
p.length,f=0;f<t;f++)var m=p[f],l=/>\s+</.exec(m),v=l[0].replace(RegExp("\\s","gi"),"&nbsp;"),m=m.replace(l,v),c=c.replace(p[f],m);if(p=c.match(reg_exp2))for(t=p.length,f=0;f<t;f++)m=p[f],l=/>\s+</.exec(m),v=l[0].replace(RegExp("\\s","gi"),"&nbsp;"),m=m.replace(l,v),c=c.replace(p[f],m)}catch(y){c=e}}for(d=0;d<k;d++)for(f=0;f<k;f++)b=RegExp("/"+g[d]+">\\s<"+g[f],"gi"),c=c.replace(b,"/"+g[d]+">&nbsp;<"+g[f]),b=RegExp("/"+g[d]+">\\s\\n<"+g[f],"gi"),c=c.replace(b,"/"+g[d]+">&nbsp;<"+g[f]);return c}catch(u){return a}}};
function DEXT_CONFIG(){this.defaultLineHeight=this.defaultFontFamily=this.defaultFontSize=this.lang=this.dext_path="";this.accessibility="0";this.visibility=!0;this.status_bar=this.top_status_bar=this.tool_bar=this.top_menu="0";this.toSavePathURL="dext5data";this.toSaveFilePathURL="dext5file";this.saveFileFolderNameRule=this.saveFolderNameRule="YYYY/MM";this.serverDomain="";this.saveFileNameRule="GUID";this.showDialogPosition="1";this.image_convert_height=this.image_convert_width=this.image_convert_format=
"";this.image_auto_fit="0";this.productKey="";this.plugInUse="0";this.fileFieldID=this.firstLoadMessage=this.firstLoadType=this.defaultMessage="";this.printPreview="0";this.basePrintFooter=this.basePrintHeader=this.printFooter=this.printHeader="";this.sourceViewtype="0";this.nextTabElementId=this.userCssUrl="";this.xhtml_value=this.empty_tag_remove=this.paste_image_base64="0";this.system_title="DEXT5";this.view_mode_auto_height="0";this.changeMultiValueMode="doctype";this.tableAutoAdjust="1";this.trustSites=
"";this.contextMenuDisable="0";this.userFieldValue=this.userFieldID=this.enterTag="";this.mimeCharset="euc-kr";this.mimeConentEncodingType="3";this.mimeLocalOnly=this.mimeFileTypeFilter="1";this.mimeRemoveHeader="0";this.imgDefaultHeight=this.imgDefaultWidth=this.mimeBaseURL=this.userImageDlgStyle=this.userOpenDlgInitDir=this.userOpenDlgType=this.userOpenDlgTitle="";this.officeLineFix="1";this.useLog="0";this.EditorTabDisable="";this.style={skinName:"blue",width:"100%",height:"600px",InitVisible:!0,
isFontSizeUse:!0,defaultMinHeight:"300px",iconName:"icon"};this.webPath={image:DEXT5.rootPath+"images/editor/",page:DEXT5.rootPath+"pages/",js:DEXT5.rootPath+"js/",css:DEXT5.rootPath+"css/",include:DEXT5.rootPath+"include/",config:DEXT5.rootPath+"config/"};this.holderID="";this.config_url=DEXT5.rootPath+"config/dext_editor.xml";this.emoticon_url=DEXT5.rootPath+"config/dext_emoticon.xml";this.forms_url=DEXT5.rootPath+"config/dext_formlist.xml";this.post_url=DEXT5.rootPath+"handler/upload_handler.ashx";
this.proxy_url=this.post_url_save_for_notes="";this.plugin_root=DEXT5.rootPath+"plugin/";this.plugin_version=DEXT5.cabVersion;this.editor_url=DEXT5.isRelease?DEXT5.rootPath+"pages/editor_release.html":DEXT5.rootPath+"pages/editor.html";this.pages={find:"editor_find.html",replace:"editor_replace.html",image:"editor_image.html",horizontal_line:"editor_horizontal_line.html",bg_image:"dext_bg_image.html",doc_bg_img:"editor_doc_bg_img.html",flash:"editor_flash.html",media:"editor_media.html",table:"editor_table.html",
table_property:"editor_table_property.html",cell_property:"editor_cell_property.html",insert_row_column:"editor_insert_row_column.html",row_property:"editor_row_property.html",column_property:"editor_column_property.html",emoticon:"editor_emoticon.html",bookmark:"editor_bookmark.html",iframe:"editor_iframe.html",hyperlink:"editor_hyperlink.html",split_cell:"editor_split_cell.html",about:"editor_about.html",symbol:"editor_symbol.html",setting:"editor_setting.html",template:"editor_template.html",tool_replace:"editor_tool_replace.html",
insert_link_media:"editor_insert_link_media.html",m_image:"editor_m_image.html",m_emoticon:"editor_m_emoticon.html",cell_border:"editor_cell_border.html",paste_dialog:"editor_paste.html",shortcut:"editor_shortcut.html",layout:"editor_layout.html",insert_file:"editor_insert_file.html"};this.mode=this.editor_id=this.xss_use=this.xss_remove_events=this.xss_remove_tags=this.replace_tagname="";this.mimeUse="0";this.zIndex=1E4;this.autoSave=0;this.ruler={use:"0",view:"0",rulerInitPosition:"0",viewPointer:"1",
viewGuideLine:"1"};this.editorborder="1";this.imageBaseUrl=this.custom_code="";this.allowMediaFileType=[];this.allowImageFileType=[];this.allowFlashFileType=[];this.allowInsertFileType=[];this.attachFileImage="1";this.tableClassList=[];this.tableLineStyleList=[];this.tableDefaultTdHeight=this.tableDefaultClass=this.tableDefaultHeight=this.tableDefaultWidth="";this.tableLineStyleValue={};this.tableLineStyleValue._solid="border-top: 1px solid #5d5d5d;";this.tableLineStyleValue._dotted="border-top: 1px dotted #5d5d5d;";
this.tableLineStyleValue._dashed="border-top: 1px dashed #5d5d5d;";this.tableLineStyleValue._double="border-top: 3px double #5d5d5d;";this.tableLineStyleValue._groove="border: 3px groove #e1e1e1;";this.tableLineStyleValue._ridge="border: 3px ridge #e1e1e1;";this.tableLineStyleValue._inset="border: 3px inset #e1e1e1;";this.tableLineStyleValue._outset="border: 3px outset #e1e1e1;";this.tableLineStyleValue._none="border: 1px none #5d5d5d;";this.tableLineStyleValue._hidden="border: 1px none #5d5d5d;";
this.tableDefaultInoutdent=20;this.tableNoResizeClass=this.tableInitInoutdent="";this.tableColMaxCount=this.tableRowMaxCount="13";this.focusInitObjId="";this.setDefaultStyle={value:"0",body_id:"dext_body"};this.SymbolUrl="../js/editor_symbol.js";this.customEventCmd={image:{ondbclick:""}};this.ieCompatible="";this.autoUrlDetect="1";this.scrollOverflow=this.pasteRemoveEmptyTag="0";this.disableKeydown=this.autoBodyFit=this.disableTabletap=this.defaultImemode="";this.dragAndDropAllow="0";this.limitPasteHtmlLength=
{value:"0",length:13E5};this.wrapPtagToSource=this.pasteToImage="0"}function isExistEditorName(a){if(void 0==a||""==a)return 1;a=DEXT5.DEXTMULTIPLE["dext_frame_"+a];return void 0==a||null==a?0:2}function getNewNextEditorName(a){var c="",c=a.split("_"),b=c.length;1<b&&(a=a.replace("_"+c[b-1],""));c=a+getNextEditorNumber();0<isExistEditorName(c)&&(c=getNewNextEditorName(c));return c}var getNextEditorNumber=function(){var a=0;return function(){return"_"+ ++a}}();
function Dext5editor(a){var c=isExistEditorName(a);if(1==c)alert("editor's name is empty. Please, check editor's name");else{if(2==c)if("1"==DEXT5.config.IgnoreSameEditorName)a=getNewNextEditorName(a);else{alert("editor's name is already exist. Please, check editor's name");return}""!=DEXT5.config.RootPath&&(DEXT5.rootPath=DEXT5.config.RootPath);var b=new DEXT_CONFIG;0<DEXT5.config.InitXml.length&&(b.config_url=DEXT5.rootPath+"config/"+DEXT5.config.InitXml);b.config_url+="?t="+(new Date).getTime();
var e=DEXT5.ajax.loadXml(b.config_url);if(null==e)alert("ErrCode : 1000");else{DEXT5.DEXTMULTIPLE["dext_frame_"+a]=a;var h=DEXT5.util.xml.getNode(e,"xss_protection"),g=DEXT5.util.xml.getNodeValue(h,"xss_use"),k=DEXT5.util.xml.getNodeValue(h,"xss_remove_tags"),d=DEXT5.util.xml.getNodeValue(h,"xss_remove_events");""==g&&(g="0");""!=DEXT5.config.zXssUse&&(g=DEXT5.config.zXssUse);b.xss_use=g;""!=DEXT5.config.zXssRemoveTags&&(k=DEXT5.config.zXssRemoveTags);b.xss_remove_tags=k.toLowerCase();""!=DEXT5.config.zXssRemoveEvents&&
(d=DEXT5.config.zXssRemoveEvents);"all"==d.toLowerCase()?b.xss_remove_events="onabort,onactivate,onafterprint,onafterupdate,onbeforeactivate,onbeforecopy,onbeforecut,onbeforedeactivate,onbeforeeditfocus,onbeforepaste,onbeforeprint,onbeforeunload,onbeforeupdate,onbegin,onblur,onbounce,oncellchange,onchange,onclick,oncontentready,oncontentsave,oncontextmenu,oncontrolselect,oncopy,oncut,ondataavailable, ondatasetchanged, ondatasetcomplete, ondblclick, ondeactivate,ondetach, ondocumentready, ondrag, ondragdrop, ondragend,ondragenter,ondragleave,ondragover,ondragstart,ondrop,onend,onerror,onerrorupdate,onfilterchange,onfinish,onfocus,onfocusin,onfocusout,onhelp,onhide,onkeydown,onkeypress,onkeyup,onlayoutcomplete,onload,onlosecapture,onmediacomplete,onmediaerror,onmedialoadfailed,onmousedown,onmouseenter,onmouseleave,onmousemove,onmouseout,onmouseover,onmouseup,onmousewheel,onmove,onmoveend,onmovestart,onopenstatechange,onoutofsync,onpaste,onpause,onplaystatechange,onpropertychange,onreadystatechange,onrepeat,onreset,onresize,onresizeend,onresizestart,onresume,onreverse,onrowclick,onrowenter,onrowexit,onrowout,onrowover,onrowsdelete,onrowsinserted,onsave,onscroll,onseek,onselect,onselectionchange,onselectstart,onshow,onstart,onstop,onsubmit,onsyncrestored,ontimeerror,ontrackchange,onunload,onurlflip":
b.xss_remove_events=d.toLowerCase();1E4<=parseInt(DEXT5.config.zIndex,10)&&(b.zIndex=parseInt(DEXT5.config.zIndex,10));b.editorborder=""==DEXT5.config.EditorBorder?"1":DEXT5.config.EditorBorder;var f=DEXT5.util.xml.getNode(e,"setting"),p=DEXT5.util.xml.getNodeValue(f,"width"),t=DEXT5.util.xml.getNodeValue(f,"height"),m=DEXT5.util.xml.getNodeValue(f,"skinname"),l=DEXT5.util.xml.getNodeValue(f,"lang"),v=DEXT5.util.xml.getNodeValue(f,"accessibility"),y=DEXT5.util.xml.getNodeValue(f,"showdialog_pos"),
u=DEXT5.util.xml.getNodeValue(f,"source_viewtype"),w=DEXT5.util.xml.getNodeValue(f,"user_css_url"),F=DEXT5.util.xml.getNodeValue(f,"xhtml_value"),G=DEXT5.util.xml.getNodeValue(f,"system_title"),H=DEXT5.util.xml.getNodeValue(f,"view_mode_auto_height"),P=DEXT5.util.xml.getNodeValue(f,"table_auto_adjust"),W=DEXT5.util.xml.getNodeValue(f,"context_menu_disable"),I=DEXT5.util.xml.getNodeValue(f,"enter_tag"),X=DEXT5.util.xml.getNodeValue(f,"office_linefix"),Y=DEXT5.util.xml.getNodeValue(f,"editor_tab_disable");
b.EditorTabDisable=""==DEXT5.config.EditorTabDisable?0==Y.length?b.EditorTabDisable:Y:DEXT5.config.EditorTabDisable;b.contextMenuDisable="1"==W?"1":"0";var Z=DEXT5.util.xml.getNodeValue(f,"ie_compatible");""!=Z&&(b.ieCompatible=Z);var $=DEXT5.util.xml.getNodeValue(f,"auto_url_detect");""!=$&&(b.autoUrlDetect=$);b.officeLineFix=""==DEXT5.config.officeLineFix?0==X.length?b.officeLineFix:X:DEXT5.config.officeLineFix;"1"==DEXT5.util.xml.getNodeValue(f,"paste_remove_empty_tag")&&(b.pasteRemoveEmptyTag=
"1");var aa=DEXT5.util.xml.getNodeValue(f,"scroll_overflow");""!=aa&&(b.scrollOverflow=aa);"1"==DEXT5.util.xml.getNodeValue(f,"default_imemode")&&(b.defaultImemode="1");"1"==DEXT5.util.xml.getNodeValue(f,"disable_tabletap")&&(b.disableTabletap="1");"1"==DEXT5.util.xml.getNodeValue(f,"auto_body_fit")&&(b.autoBodyFit="1");"1"==DEXT5.util.xml.getNodeValue(f,"disable_keydown")&&(b.disableKeydown="1");var Ka=DEXT5.util.xml.getNode(f,"custom_event"),La=DEXT5.util.xml.getNode(Ka,"image"),ba=DEXT5.util.xml.getNodeValue(La,
"ondbclick");""!=ba&&(b.customEventCmd.image.ondbclick=ba);var Ma=DEXT5.util.xml.getNode(f,"pageurl"),Na=DEXT5.util.xml.getNode(Ma,"script"),ca=DEXT5.util.xml.getNodeValue(Na,"symbol");""!=ca&&(b.SymbolUrl=ca);var Q=DEXT5.util.xml.getNodeValue(f,"icon_name");""!=Q&&(b.style.iconName=Q,DEXT5.config.IconName=Q);var da=DEXT5.util.xml.getNodeValue(f,"image_base_url");""!=da&&(b.imageBaseUrl=da);if("1"==DEXT5.util.xml.getNodeValue(f,"use_ruler")){b.ruler.use="1";b.ruler.view="1";var E=DEXT5.util.xml.getNode(f,
"use_ruler");E.getAttribute("ruler_init_position")&&""!=E.getAttribute("ruler_init_position")&&(b.ruler.rulerInitPosition=E.getAttribute("ruler_init_position"));E.getAttribute("view_pointer")&&"1"!=E.getAttribute("view_pointer")&&(b.ruler.viewPointer="0");E.getAttribute("view_guide_line")&&"1"!=E.getAttribute("view_guide_line")&&(b.ruler.viewGuideLine="0")}if(""==b.enterTag){if(I=I.toLocaleLowerCase(),"br"==I||"div"==I)b.enterTag=I}else b.enterTag=b.enterTag.toLocaleLowerCase(),b.enterTag="br"!=b.enterTag&&
"div"!=b.enterTag?"":I;var R=DEXT5.util.xml.getNodeValue(f,"set_default_style");if(""!=R&&"0"!=R){b.setDefaultStyle.value=R;var ea=DEXT5.util.xml.getNode(f,"set_default_style");""!=ea.getAttribute("body_id")&&(b.setDefaultStyle.body_id=ea.getAttribute("body_id"))}var fa=DEXT5.util.xml.getNodeValue(f,"drag_and_drop_allow");"1"==fa&&(b.dragAndDropAllow=fa);if("1"==DEXT5.util.xml.getNodeValue(f,"limit_paste_html_length")){b.limitPasteHtmlLength.value="1";var ga=DEXT5.util.xml.getNode(f,"limit_paste_html_length");
""!=ga.getAttribute("length")&&(b.limitPasteHtmlLength.length=parseInt(ga.getAttribute("length"),10))}"1"==DEXT5.util.xml.getNodeValue(f,"wrap_ptag_to_source")&&(b.wrapPtagToSource="1");"1"==DEXT5.util.xml.getNodeValue(f,"paste_to_image")&&(b.pasteToImage="1");var s=DEXT5.util.xml.getNode(e,"uploader_setting"),J=DEXT5.util.xml.getNodeValue(s,"develop_langage"),z=DEXT5.util.xml.getNodeValue(s,"handler_url"),ha=DEXT5.util.xml.getNodeValue(s,"to_save_path_url"),ia=DEXT5.util.xml.getNodeValue(s,"to_save_file_path_url"),
B=DEXT5.util.xml.getNodeValue(s,"save_foldername_rule"),C=DEXT5.util.xml.getNodeValue(s,"save_file_foldername_rule"),Oa=DEXT5.util.xml.getNodeValue(s,"server_domain"),S=DEXT5.util.xml.getNodeValue(s,"save_filename_rule"),Pa=DEXT5.util.xml.getNodeValue(s,"image_convert_format"),Qa=DEXT5.util.xml.getNodeValue(s,"image_convert_width"),Ra=DEXT5.util.xml.getNodeValue(s,"image_convert_height"),Sa=DEXT5.util.xml.getNodeValue(s,"image_auto_fit"),ja=DEXT5.util.xml.getNodeValue(s,"handler_url_save_for_notes");
""!=ja&&(b.post_url_save_for_notes=ja);var N=DEXT5.util.xml.getNode(e,"extra_setting");N&&(b.paste_image_base64=DEXT5.util.xml.getNodeValue(N,"paste_image_base64"),b.empty_tag_remove=DEXT5.util.xml.getNodeValue(N,"empty_tag_remove"),b.custom_code=DEXT5.util.xml.getNodeValue(N,"custom_code"),DEXT5.config.CustomCode=b.custom_code);b.serverDomain=Oa;0<DEXT5.config.ServerDomain.length&&(b.serverDomain=DEXT5.config.ServerDomain);0<DEXT5.config.HandlerUrl.length&&(z=DEXT5.config.HandlerUrl);b.image_convert_format=
Pa;b.image_convert_width=Qa;b.image_convert_height=Ra;b.image_auto_fit=Sa;var ka=DEXT5.util.xml.getNodeValue(s,"allow_media_file_type");if(0<ka.length)for(var la=ka.split(","),Ta=la.length,n=0;n<Ta;n++)b.allowMediaFileType.push(la[n]);else b.allowMediaFileType=["wmv","asf"];var ma=DEXT5.util.xml.getNodeValue(s,"allow_image_file_type");if(0<ma.length)for(var na=ma.split(","),Ua=na.length,n=0;n<Ua;n++)b.allowImageFileType.push(na[n]);else b.allowImageFileType=["jpg","jpeg","png","gif","bmp"];var oa=
DEXT5.util.xml.getNodeValue(s,"allow_flash_file_type");if(0<oa.length)for(var pa=oa.split(","),Va=pa.length,n=0;n<Va;n++)b.allowFlashFileType.push(pa[n]);else b.allowFlashFileType=["swf"];var qa=DEXT5.util.xml.getNodeValue(s,"allow_insert_file_type");if(0<qa.length)for(var ra=qa.split(","),Wa=ra.length,n=0;n<Wa;n++)b.allowInsertFileType.push(ra[n]);else b.allowInsertFileType="txt doc docx xls xlsx ppt pptx hwp pdf".split(" ");"0"==DEXT5.util.xml.getNodeValue(s,"attach_file_image")&&(b.attachFileImage=
"0");var q=DEXT5.util.xml.getNode(f,"table_property");q&&(q.getAttribute("width")&&(b.tableDefaultWidth=q.getAttribute("width")),q.getAttribute("height")&&(b.tableDefaultHeight=q.getAttribute("height")),q.getAttribute("class")&&(b.tableDefaultClass=q.getAttribute("class")),q.getAttribute("inoutdent")&&(b.tableDefaultInoutdent=q.getAttribute("inoutdent")),q.getAttribute("init_inoutdent")&&(b.tableInitInoutdent=q.getAttribute("init_inoutdent")),q.getAttribute("td_height")&&(b.tableDefaultTdHeight=q.getAttribute("td_height")),
q.getAttribute("row_max_count")&&(b.tableRowMaxCount=q.getAttribute("row_max_count")),q.getAttribute("col_max_count")&&(b.tableColMaxCount=q.getAttribute("col_max_count")));var sa=DEXT5.util.xml.getNodeValue(q,"class_list");if(0<sa.length)for(var ta=sa.split(","),Xa=ta.length,n=0;n<Xa;n++)b.tableClassList.push(ta[n]);var ua=DEXT5.util.xml.getNodeValue(q,"line_style");if(0<ua.length)for(var va=ua.split(","),Ya=va.length,n=0;n<Ya;n++)b.tableLineStyleList.push(va[n]);var wa=DEXT5.util.xml.getNodeValue(q,
"no_resize_class");0<wa.length&&(b.tableNoResizeClass=wa);var K=DEXT5.util.xml.getNode(f,"img_default_size");K&&K.getAttribute("width")&&(b.imgDefaultWidth=K.getAttribute("width"));K&&K.getAttribute("height")&&(b.imgDefaultHeight=K.getAttribute("height"));b.style.width=""==DEXT5.config.Width?0==p.length?b.style.width:p:DEXT5.config.Width;b.style.height=""==DEXT5.config.Height?0==t.length?b.style.height:t:DEXT5.config.Height;b.style.skinName=""==DEXT5.config.SkinName?0==m.length?b.style.skinName:m:
DEXT5.config.SkinName;if("random"==b.style.skinName){var Za=Math.floor(11*Math.random()),$a=DEXT5.util.getSkinNames();b.style.skinName=$a[Za]}b.defaultMessage=""==DEXT5.config.DefaultMessage?"":DEXT5.config.DefaultMessage;b.firstLoadType=""==DEXT5.config.FirstLoadType?"":DEXT5.config.FirstLoadType;b.firstLoadMessage=""==DEXT5.config.FirstLoadMessage?"":DEXT5.config.FirstLoadMessage;b.fileFieldID=""==DEXT5.config.FileFieldID?"Filedata":DEXT5.config.FileFieldID;b.nextTabElementId=""==DEXT5.config.NextTabElementId?
"":DEXT5.config.NextTabElementId;b.userFieldID=""==DEXT5.config.UserFieldID?"Userdata":DEXT5.config.UserFieldID;b.userFieldValue=DEXT5.config.UserFieldValue;b.toSavePathURL=""==DEXT5.config.ToSavePathURL?0==ha.length?b.toSavePathURL:ha:DEXT5.config.ToSavePathURL;b.toSaveFilePathURL=""==DEXT5.config.ToSaveFilePathURL?0==ia.length?b.toSaveFilePathURL:ia:DEXT5.config.ToSaveFilePathURL;b.sourceViewtype="1"==u||"2"==u?u:"0";5<w.length&&"http"==w.substring(0,4).toLowerCase()?b.userCssUrl=w:b.userCssUrl=
"";b.xhtml_value="1"==F?"1":"0";""!=G&&(b.system_title="0"==G?"":G);b.view_mode_auto_height="1"==H?"1":"0";""!=DEXT5.config.ChangeMultiValueMode&&(b.changeMultiValueMode=DEXT5.config.ChangeMultiValueMode);"0"==P&&(b.tableAutoAdjust="0");0<DEXT5.config.mimeCharset.length&&(b.mimeCharset=DEXT5.config.mimeCharset);0<DEXT5.config.mimeConentEncodingType.length&&(b.mimeConentEncodingType=DEXT5.config.mimeConentEncodingType);0<DEXT5.config.mimeLocalOnly.length&&(b.mimeLocalOnly=DEXT5.config.mimeLocalOnly);
0<DEXT5.config.mimeRemoveHeader.length&&(b.mimeRemoveHeader=DEXT5.config.mimeRemoveHeader);0<DEXT5.config.mimeFileTypeFilter.length&&(b.mimeFileTypeFilter=DEXT5.config.mimeFileTypeFilter);0<DEXT5.config.userOpenDlgTitle.length&&(b.userOpenDlgTitle=DEXT5.config.userOpenDlgTitle);0<DEXT5.config.userOpenDlgType.length&&(b.userOpenDlgType=DEXT5.config.userOpenDlgType);0<DEXT5.config.userOpenDlgInitDir.length&&(b.userOpenDlgInitDir=DEXT5.config.userOpenDlgInitDir);0<DEXT5.config.userImageDlgStyle.length&&
(b.userImageDlgStyle=DEXT5.config.userImageDlgStyle);0<DEXT5.config.mimeBaseURL.length&&(b.mimeBaseURL=DEXT5.config.mimeBaseURL);"0"==y&&(b.showDialogPosition="0");l=l.toLowerCase();b.lang=""==l?"ko":l;if(2<=DEXT5.config.InitLang.length){var ab=DEXT5.config.InitLang.toLowerCase();b.lang=ab}b.accessibility=0==v.length?"0":v;if("YYYYMMDD/"==B||"YYYYMM/"==B||"YYYY/"==B||"YYYY/MM/"==B||"YYYY/MM/DD/"==B||"/"==B||""==B)b.saveFolderNameRule=B;if("YYYYMMDD/"==C||"YYYYMM/"==C||"YYYY/"==C||"YYYY/MM/"==C||"YYYY/MM/DD/"==
C||"/"==C||""==C)b.saveFileFolderNameRule=C;if("GUID"==S||"DATETIME"==S)b.saveFileNameRule=S;var xa=DEXT5.util.xml.getNodeValue(f,"topmenu"),L=DEXT5.util.xml.getNodeValue(f,"toolbar"),ya=DEXT5.util.xml.getNodeValue(f,"topstatusbar"),za=DEXT5.util.xml.getNodeValue(f,"statusbar"),Aa=DEXT5.util.xml.getNodeValue(f,"resizebar");b.top_menu="1"==xa?xa:"0";b.tool_bar="1"==L||"2"==L||"3"==L||"4"==L?L:"0";b.top_status_bar=""!=ya?ya:"1";b.status_bar="1"==za?za:"0";b.resize_bar="0"==Aa?Aa:"1";""!=DEXT5.config.zTopMenu&&
(b.top_menu=DEXT5.config.zTopMenu);""!=DEXT5.config.zToolBar&&(b.tool_bar=DEXT5.config.zToolBar);""!=DEXT5.config.zTopStatusBar&&(b.top_status_bar=DEXT5.config.zTopStatusBar);""!=DEXT5.config.zStatusBar&&(b.status_bar=DEXT5.config.zStatusBar);""!=DEXT5.config.Mode&&(b.mode=DEXT5.config.Mode);var Ba=parseInt(DEXT5.util.xml.getNodeValue(f,"auto_save"),10);0<Ba&&(b.autoSave=Ba);var M="",M=0==z.length?DEXT5.rootPath:"/"==z.substring(0,1)?location.protocol+"//"+location.host:4<z.length&&"http"==z.substring(0,
4).toLowerCase()?"":DEXT5.rootPath;b.style.InitVisible=DEXT5.config.InitVisible;if(0==z.length)switch(J.toUpperCase()){case "JSP":b.post_url=M+"handler/upload_handler.jsp";break;case "PHP":b.post_url=M+"handler/upload_handler.php";break;default:b.post_url=M+"handler/upload_handler.ashx"}else{if(4<z.length&&"http"==z.substring(0,4).toLowerCase()&&z.match(/:\/\/(.[^\/]+)/)[1]!=window.location.host){var O="";switch(J.toUpperCase()){case "JSP":O=DEXT5.rootPath+"handler/upload_handler.jsp";break;case "PHP":O=
DEXT5.rootPath+"handler/upload_handler.php";break;default:O=DEXT5.rootPath+"handler/upload_handler.ashx"}b.proxy_url=O}b.post_url=M+z}""!=DEXT5.config.focusInitObjId&&(b.focusInitObjId=DEXT5.config.focusInitObjId);var A=DEXT5.util.xml.getNode(e,"license"),bb=DEXT5.util.xml.getNodeValue(A,"product_key"),Ca=DEXT5.util.xml.getNodeValue(A,"license_plugin"),Da=DEXT5.util.xml.getNodeValue(A,"plugin_use"),T=DEXT5.util.xml.getNodeValue(A,"plugin_version"),cb=DEXT5.util.xml.getNodeValue(A,"print_preview"),
Ea=DEXT5.util.xml.getNodeValue(A,"print_header"),Fa=DEXT5.util.xml.getNodeValue(A,"print_footer"),Ga=DEXT5.util.xml.getNodeValue(A,"mime_use"),db=DEXT5.util.xml.getNodeValue(A,"trust_sites");b.LicenseKey=DEXT5.util.xml.getNodeValue(A,"license_key");b.printPreview="1"==cb?"1":"0";b.printHeader=Ea;b.printFooter=Fa;b.basePrintHeader=Ea;b.basePrintFooter=Fa;b.trustSites=db;b.productKey=bb;""!=Ca&&(b.plugin_root=Ca);b.plugInUse=""==DEXT5.config.pluginUse?0==Da.length?b.plugInUse:Da:DEXT5.config.pluginUse;
b.mimeUse=""==DEXT5.config.mimeUse?0==Ga.length?b.mimeUse:Ga:DEXT5.config.mimeUse;null!=T&&7<=T.length&&(b.plugin_version=T);if("0"==b.plugInUse&&""==b.proxy_url&&("NET"==J.toUpperCase()||"JSP"==J.toUpperCase()||"PHP"==J.toUpperCase()||"ASP"==J.toUpperCase())){var U=DEXT5.ajax.load(b.post_url+"?dext=test");"CCODE_001"==b.custom_code&&(U=DEXT5.ajax.load(b.post_url+"?hello=test"));if(null==U||""==U){var x="",V=0<DEXT5.config.InitXml.length?V:"dext_editor.xml";"ko"==b.lang?(x="Editor\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc544\ub798 URL \uc811\uadfc\uc774 \uc720\ud6a8\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\n",
x+=b.post_url+"\n\n",x+=V+" \ud30c\uc77c\uc758 uploader_setting \uc139\uc158\uc758 <develop_langage>\uc640 <handler_url> \uc124\uc815\uac12\uc744 \ud655\uc778\ud558\uc138\uc694."):(x="Editor's setting is not correct. Access the following URL is not valid.\n\n",x+=b.post_url+"\n\n",x+='Please check the settings, <handler_url> and <develop_langage> in "uploader_setting" section in the "'+V+'."');alert(x);return}}b.useLog="1"==DEXT5.config.useLog?"1":"0";this.editor=null;b.editor_id=a;this.FrameID="dext_frame_"+
a;b.holderID="dext_frame_holder"+a;var D="",Ha=b.style.height;!1==b.style.InitVisible&&(Ha="1px");D='<div id="'+b.holderID+'" style="width:'+b.style.width+"; height:"+Ha+"; ";if(DEXT5.browser.iOS||DEXT5.browser.mobile)D+=" overflow:scroll; overflow-x:hidden; -webkit-overflow-scrolling:touch; ";D+='"></div>';if(""!=DEXT5.config.EditorHolder){var Ia=document.getElementById(DEXT5.config.EditorHolder);Ia?Ia.innerHTML=D:document.write(D)}else document.write(D);var eb=document.getElementById(b.holderID),
r;try{r=document.createElement("<iframe frameborder='0' scrolling='no'>")}catch(gb){r=document.createElement("iframe"),r.setAttribute("frameborder","0"),r.setAttribute("scrolling","no")}r.setAttribute("id",this.FrameID);r.style.width="100%";r.style.height="100%";-1<b.style.height.indexOf("%")&&(r.style.minHeight=b.style.defaultMinHeight);if(DEXT5.browser.iOS||DEXT5.browser.mobile)r.style.overflow="hidden",r.style.display="inline-block";r.width="100%";r.height="100%";eb.appendChild(r);var fb=this,
Ja=function(){try{r.contentWindow.dext_frame_loaded_event(a,b,fb);var c=window.document,e=c.getElementsByTagName("head")[0],d=c.createElement("link");d.type="text/css";d.rel="stylesheet";d.href=b.webPath.css+"editor_popup.css";e.appendChild(d)}catch(f){alert("ErrCode : 1001")}};r.addEventListener?r.addEventListener("load",Ja,!1):r.attachEvent&&r.attachEvent("onload",Ja);r.src=b.editor_url;""!=b.custom_code&&DEXT5.util.CustomSetting("function",b.custom_code,b)}}}
function CustomSettingFunction(a){"CCODE_001"==a.custom_code&&(a.empty_tag_remove="1",a.sourceViewtype="1",a.system_title="",a.tableAutoAdjust="0",a.accessibility="-1",a.tool_bar="2",a.top_menu="1",a.setDefaultStyle.value="2",a.setDefaultStyle.body_id="hello_body",a.emoticon_url=DEXT5.rootPath+"config/hello_emoticon.xml",a.forms_url=DEXT5.rootPath+"config/hello_formlist.xml")}
function CustomRemoveItem(a){var c=[];"CCODE_001"==a&&(c="save pagebreak copy cut paste doc_bg_image insert_link_media media_create entity iframe_create flash_create table_row_clone about insert_row_column grid tool_replace convert_table_to_text table_tool table_indent table_outdent row_property column_property align_vertical".split(" "));return c}
function replacePtOrCmToPx(a){try{for(var c=a.toLowerCase().split(" "),b=c.length,e,h,g="",k=0;k<b;k++){var d=c[k];-1<d.indexOf("pt")?(e=4*parseFloat(d)/3,0<e&&1>e&&(e=1),0>e&&(e=0),h=Math.round(e)+"px",g=""!=g?g+" "+h:h):-1<d.indexOf("cm")?(_cm=37.795275593333*parseFloat(d),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),h=Math.round(_cm)+"px",g=""!=g?g+" "+h:h):g=""!=g?g+" "+d:d}return""!=g?g:a}catch(f){return a}}window.DEXT5&&"samsung.net"==document.domain&&(window.HELLO=window.DEXT5,HelloEditor=Dext5editor);
